### ISSUE TITLE
Az angol fordítés szükségtelen

### ISSUE THREAD

**Issue by szepeviktor** [thepinecode/simplepay-gateway#12]
Mert a forráskódban is angolul van.
A WP core mindig parse-olja és betölti az en_US fordítást, ha angolul fut.

Törölhető a két fájl `languages/pine-simplepay-en_US.*`

**Comment by iamgergo** [comment]
Rendben, töröltem.

Köszi!

**Comment by szepeviktor** [comment]
https://github.com/thepinecode/simplepay-gateway/commit/226219e85428a3234c9fa1ee78625514dc2f9937
