### ISSUE TITLE
Szakértői telepítés Composer-ral

### ISSUE THREAD

**Issue by szepeviktor** [thepinecode/simplepay-gateway#17]
Akik felelősen és fenntarthatóan kívánnak WordPress-t futtatni, azok [Composer-ral](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/johnpbloch-composer.json#L5-L12) fogják telepíteni: core, bővítmények, sablon.
Lehet, publikálni kéne magunkat.

**Comment by iamgergo** [comment]
A composeres autoload és a bővítmény autoloadere nem ütné egymást?

**Comment by szepeviktor** [comment]
De ütné egymás, HA használnánk a Composer autoloader-ét.

- Composer autoloader nélkül teszük közzé: nem írjuk a JSON fájlba, hogy `"autoload":`
- vagy írunk egy feltételt a mi autoloader-ünk betöltéséhez

**Comment by iamgergo** [comment]
Ez a composer JSON akkor jó lehet?

**Comment by szepeviktor** [comment]
Küldtem PR-t.
Érdemes lenne a README-ben ezt megemlíteni.

**Comment by szepeviktor** [comment]
más: Nincs nagy felhozatal: https://github.com/topics/simplepay

**Comment by iamgergo** [comment]
Miért nem talál releaset a composer badge?

**Comment by szepeviktor** [comment]
Biztos elég jogot adtál neki GitHub-on?

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/73192930-1b428e80-412a-11ea-8df2-0130d2cb229f.png)

**Comment by iamgergo** [comment]
Ezek a jogosultságok vannak.

**Comment by szepeviktor** [comment]
Hát ehhez nem értek, próbáld meg megnyomni az Update gombot, vagy töröld le a csomagot és vedd fel újra.

**Comment by szepeviktor** [comment]
Valami nagy baj lehet

![kép](https://user-images.githubusercontent.com/952007/73195371-09fb8100-412e-11ea-8951-7b319ec2efce.png)

**Comment by iamgergo** [comment]
Újra hozzáadtam, szerintem pont akkor csekkoltad.
Hát ez nem akar menni...nem tudom mi lehet a baja.

**Comment by iamgergo** [comment]
Egyenlőre hanyagoljuk a composert, ha ez nem megy rendesen.

**Comment by szepeviktor** [comment]
Pedig a GitHub API is rendesen mutatja a release-eket https://api.github.com/repos/thepinecode/simplepay-gateway/releases

**Comment by iamgergo** [comment]
Nem tudom mi lehet a gond, de ha kiderül akkor visszarakjuk. Addig nincs értelme.

**Comment by szepeviktor** [comment]
Most a packagist JSON-jában láttam tag-eket :)
