### ISSUE TITLE
CRITICAL Uncaught Error: Call to a member function

### ISSUE THREAD

**Issue by gefusz** [thepinecode/simplepay-gateway#23]
A fizetést követően a SimplaPay IPN kommunikációs hibát dob:

Call to a member function get_currency() on boolean in /wp-content/plugins/simplepay-gateway-master/src/Gateway.php:166

Ha a megadott IPN url-t megpróbálom nyitni akkor is ugyan ezeket a php hibákat dobja.
Felhasználói oldalról ez ugye nem látszik, mert az oldalon sikeresen végbemegy a rendelés.

Így nem tudják jóváhagyni! Van erre valami megoldás?

**Comment by iamgergo** [comment]
Szia!

Köszi az észrevételt! Ilyennel még nem találkoztam, de úgy néz ki, hogy a rendelés nem létezik azzal a paraméterrel amelyet az IPN visszaad.

De való igaz, hogy az if-else ágban is van egy logikai hiba, azt a mai nap folyamán javítom és jelzek.

**Comment by iamgergo** [comment]
@gefusz Frissítettem a kódot, elvileg most nem kellene ilyen hibát dobnia. Meg tudod erősíteni?

**Comment by gefusz** [comment]
@iamgergo Kipróbáltam és most már a WC log-ban nincs benne a hiba.
A simplepay felületén is 200-as a HTTP válasz kódja és le is zárja de még azt írja, hogy
"Hibás tartalom a válaszban"
Eredmény CONTENTNOTMATCH
Signature NO_SIGNATURE
Fogadott válasz: -1
Index 2
IPN URL https://dxlabz.hu/dxredesign?wc-api=wc_gateway_simplepay-gatewayElküldött IPN tartalma {"salt":"mZTocEKK6djNCoxYNe85EGfz91KmtWbo","orderRef":"wc_order_qfFxTz4DJUo3U","method":"CARD","merchant":"OMS5346202","finishDate":"2020-05-18T12:07:50+02:00","paymentDate":"2020-05-18T12:07:37+02:00","transactionId":10294803,"status":"FINISHED"}

**Comment by kadarbence** [comment]
> @iamgergo Kipróbáltam és most már a WC log-ban nincs benne a hiba.
> A simplepay felületén is 200-as a HTTP válasz kódja és le is zárja de még azt írja, hogy
> "Hibás tartalom a válaszban"
> Eredmény CONTENTNOTMATCH
> Signature NO_SIGNATURE
> Fogadott válasz: -1
> Index 2
> IPN URL [https://dxlabz.hu/dxredesign?wc-api=wc_gateway_simplepay-gatewayElküldött](https://dxlabz.hu/dxredesign?wc-api=wc_gateway_simplepay-gatewayElk%C3%BCld%C3%B6tt) IPN tartalma {"salt":"mZTocEKK6djNCoxYNe85EGfz91KmtWbo","orderRef":"wc_order_qfFxTz4DJUo3U","method":"CARD","merchant":"OMS5346202","finishDate":"2020-05-18T12:07:50+02:00","paymentDate":"2020-05-18T12:07:37+02:00","transactionId":10294803,"status":"FINISHED"}

Ez a hiba lépett fel nálunk is:
Eredmény CONTENTNOTMATCH
Signature NO_SIGNATURE
Fogadott válasz -1
Index 8
Időpont 2020.05.18 12:58:50

**Comment by gefusz** [comment]
Szerintem a signature mező üres lehet vagy nem továbbítódik a Simplepay felé, mert azt leszámítva a többi mezőnek van értéke.

**Comment by iamgergo** [comment]
@gefusz @kadarbence  Igen, a signature mező üres, mint az összes többi, ha nem egyezik a két hash, de ebben az esetben más volt a hiba. Ha minden igaz javítottam, meg tudjátok erősíteni?

**Comment by ucsendre** [comment]
Most nálunk is előjött a fenti hiba.
`Wrong content in response, Finish, 2020.05.18 13:55:33
Result CONTENTNOTMATCH
Signature NO_SIGNATURE
Response -1
Index 2`

**Comment by ucsendre** [comment]
(Ez még a 2.2.0 verzió volt.)

**Comment by iamgergo** [comment]
A 2.2.1-el hibamentesen lefut?

**Comment by gefusz** [comment]
Ugyan az a hiba továbbra is!
Eredmény CONTENTNOTMATCH
Signature NO_SIGNATURE
Fogadott válasz -1
Index 2
Időpont 2020.05.18 15:50:33
IPN URL https://dxlabz.hu/dxredesign?wc-api=wc_gateway_simplepay-gateway
Elküldött IPN tartalma {"salt":"urgWUbY9CQVHfoUY6JbIU1haPJiRuFUu","orderRef":"wc_order_FKKvfrOLC1I7C","method":"CARD","merchant":"OMS5346202","finishDate":"2020-05-18T15:50:20+02:00","paymentDate":"2020-05-18T15:50:05+02:00","transactionId":10295203,"status":"FINISHED"}
Válasz HTTP kódja 200

**Comment by iamgergo** [comment]
Frissítve lett 2.2.1-re a bővítményt? Nekem ezzel most lefut az IPN hibamentesen.

**Comment by gefusz** [comment]
Frissítve lett igen, azzal kezdtem és utána adtam le újra rendelést!
Próbáltam az IPN küldést manuálisan is de ugyan azt a hibát dobja.

**Comment by iamgergo** [comment]
Értem, köszi!

Én is csináltam most egy újabb vásárlást. Az IPN tökéletesen lefutott. Ezt követően a WP és a SimplePay oldalán is csináltam egy-egy visszatérítést, és az IRN is lefutott ahogy kell.

Esetleg arra tudok gondolni, hogy az adatok nem megfelelő valutához, vagy mondjuk extra szóközökkel lettek metve.

**Comment by gefusz** [comment]
A fizetés nálam is sikeres, jön is róla mail, illetve a visszatérítés is működik csak a SimplePay felületén a rendelésnél továbbra is az IPN résznél feljön mint hibaüzenet.

**Comment by iamgergo** [comment]
Nem tudok mire gondolni akkor. Nem értem, hogy miért jelez hibát ha lefut a rendelés menete ahogy kell. A simplepay felületén a rendelési státusz is sikeres?

**Comment by summeritsoft** [comment]
Sziasztok! Frissítettem a 2.2.1-re és a WOO-t is a 4.1.1-re, de továbbra sem megy. Egyszerűen eldob a végén "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra." és a log-ban pedig ez van: 
2020-05-21T07:29:38+00:00 CRITICAL Uncaught Error: Call to a member function get_currency() on boolean in /var/www/vhosts/.../wp-content/plugins/simplepay-gateway-master/src/Gateway.php:166. 
Van esetleg további ötletetek, hogy mi lehet a hiba?

**Comment by gefusz** [comment]
Nálam az a probléma a 2.2.1-es frissítéssel megoldódott. De egy pár dolgot leírnék amivel mindenképp ki kell egészíteni a bővítményt, hogy azt SimplePay is jóvá tudja hagyni.

- a SimplePay logónak meg kell jelennie a fizetési opciónál és a https://simplepartner.hu/PaymentService/Fizetesi_tajekoztato.pdf linkre kell, hogy mutasson

- Kell egy rész ahol elfogadja a rendeléssel a Simplepay adatkezelési (adattovábbítási) tájékoztatóját
  ezzel a linkkel: http://simplepay.hu/vasarlo-aff

Tehát ha az IPN-es dolog ami nálam volt meg is oldódik, akkor sem lehet ezek nélkül jóváhagyatni.
Nyilván egy fejlesztő ezeket meg tudja oldani magától is de én azt javaslom, hogy annak érdekében, hogy magát a bővítményt lehessen használni anélkül is, hogy valaki értene a fejlesztéshez (html,css,php), ezekkel ki kell egészíteni.

**Comment by iamgergo** [comment]
Sziasztok, köszi a visszajelzéseke!

@summeritsoft Valóban a 2.2.1-el ennek meg kellett volna oldódnia, de a javításban nagy segítség lenne, ha tudnánk, hogy milyen értékkel tér vissza ez a sor: https://github.com/thepinecode/simplepay-gateway/blob/master/src/Gateway.php#L166

```
$order = wc_get_order(wc_get_order_id_by_order_key($payload['orderRef']))
```

Itt milyen értéket kap az `$order`? Én ezt nem tudom reprodukálni, így jól jönne a segítség.

Köszi!

@gefusz Mivel ezt sem tudom reprodukálni, itt is nagy segítség lenne kicsit több infó, esetleg egy PR ha van megoldás. Nálam az IPN és IRN is lefut, Woo és SimplePay oldalon is hibamentesen.

A jóváhagyással kapcsolatban:
- A logónak nem a fizetési kapunál kell megjelennie, hanem magán az oldalon. Erre van beépítve egy widget ami a megfelelő linkre visz. Ezt az alapján mondom, hogy ebben a formában már több helyen elfogadásra került a bővítmény.
- Az adatkezelési tájékoztató megint egy egyedi dolog. Ezt a kereskedőnek kell megoldania, és erre van is beépített woo megoldás. Tehát csak annyi a dolga, hogy az adatkezelési nyilatkozatban megadja a megfelelő adatokat vagy hivatkozik az OTP-sre.
- Valóban egyértelműbb lenne a SimplePay oldalán ha a hivatkozás a rendelés azonosítója lenne, de mindenképpen egyedi kulcs kell, mert vannak esetek amikor duplikálás fordulhat elő.

Köszi neked is, ha esetleg sikerült utánajárni az IPN-nek akkor szívesen vesszük a visszajelzést esetleg egy PR-t ha a bővítmény oldalán van a hiba.

**Comment by summeritsoft** [comment]
Kedves Gergő!

Köszi a segítséget, sajnos más okozta a hibát. "Kiheréltük" a woo űrlapot és csak a Számlázási adatokat akartuk küldeni, ti viszont a PaymentPayload_php-ban vártátok a Szállítási adatokat is (80. sor). Tanulság (azon túl, hogy a mi hibánk volt): érdemes lenne betenni a köv. verzióba egy űres mező figyelést és ha üres a Szállítási cím, akkor az OPT-felé a Számlázási adatokkal helyettesítve engedni a küldést. 

Ahogy kicseréltük az alábbi részt a PaymentPayload_php-ban, azonnal működött :)

protected static function delivery(WC_Order $order)
    {
        return [
            'city' => $order->get_billing_city(),
            'phone' => $order->get_billing_phone(),
            'state' => $order->get_billing_state(),
            'zip' => $order->get_billing_postcode(),
            'company' => $order->get_billing_company(),
            'country' => $order->get_billing_country(),
            'address' => $order->get_billing_address_1(),
            'address2' => $order->get_billing_address_2(),
            'name' => "{$order->get_billing_first_name()} {$order->get_billing_last_name()}",
        ];

Köszi a frissítést és hogy támogatást nyújtottatok a többieknek is!!!

Üdv., János

**Comment by iamgergo** [comment]
@summeritsoft Szuper, köszi a visszajelzést!

Igen, ez jó ötlet, hamarosan akkor figyelni fogjuk a szállítási címet és ha nincs használatban, akkor automatikusan a számlázási adatok kerülnek átadásra.

Köszönöm!
