### ISSUE TITLE
A SimplePay egy nem üzembiztos szolgáltatás

### ISSUE THREAD

**Issue by szepeviktor** [thepinecode/simplepay-gateway#24]
olvastam hogy ![kép](https://user-images.githubusercontent.com/952007/82556345-d673b500-9b69-11ea-9d8f-09f1cdc5dd4c.png)
gondolom ez a bővítményre vonatkozik, mert maga a gateway sajnos nem az

...ezért hasznos, ha **előbb** értesülünk az üzemzavaraikról, mint a mi vásárlóink

ebben nagy segítség, ha ezt a ping-ető szkriptet 10 percenként futtatjuk
https://gist.github.com/szepeviktor/8ff5ea1d48929b5ff1107fab4cbc45eb

Esetleg ha PHP-ban lenne, és küldene az `admin_email`-re riasztást?

**Comment by szepeviktor** [comment]
Milyen érzelmeket váltana ki belőled, ha a plugin megjelenne a WP.org-on?

**Comment by iamgergo** [comment]
Jókat. Csak aztán rágondolok az SVN-re és rosszul leszek. Ráadásul akkor az egész updatert kukába kell dobni, szóval egyenlőre nem tervezem.

**Comment by szepeviktor** [comment]
Látom, nincs is WP.org-os user-ed!

**Comment by ucsendre** [comment]
Talán valami az alábbiakhoz hasonló megoldás segíthet:
https://github.com/Seravo/git-to-wordpress-plugin-svn-pusher
https://github.com/GaryJones/wordpress-plugin-svn-deploy
https://github.com/kasparsd/wp-deploy
(én sajnos nem értek hozzá ilyen szinten)

**Comment by szepeviktor** [comment]
Köszi @ucsendre !
Ilyeneket fejlesztek.
