### ISSUE TITLE
 Virtuális termék - Hiba a fizetés feldolgozásakor. Kérlek próbáld újra. 

### ISSUE THREAD

**Issue by Csutszika** [thepinecode/simplepay-gateway#25]
Üdvözletem! 
Érdekes problémába ütköztem. Még teszt üzemben vagyunk.
Online tanfolyamokat értékesítő oldalra telepítettem a bővítményüket (máshova is felraktam már, csodásan működik!), ahol a tanfolyamok mellé opcióba rendelhet fizikai terméket is. Ha magában a tanfolyamot rendeljük meg, "Hiba a fizetés feldolgozásakor. Kérlek próbáld újra."  hibaüzenettel nem navigál át az otp oldalára. Azonban, ha választok hozzá egy fizikai terméket, minden gond nélkül. Tehát a kiszolgáló azonosító és a titkos kulcs biztosan jó. Csak megválogatja nekünk, mit fizethetünk kártyával és mit nem. A banki átutalást minden verzióra engedi. A fizikai termékeket egy Extra Product Options bővítménnyel tudja a tanfolyamhoz válogatni. Azt is kikapcsoltam, de úgy sem akarja a rendszer, hogy a tanfolyam kártyával legyen fizetve.  Wordpress, vagy Woocommerce beállítási probléma lehet? Vagy van ötletük? 
Íme egy termék, ha érdekes lehet: https://www.zsiliponline.com/termek/punkosdi-rozsa-online-akrilfesteszeti-tanfolyam-masolat/
Előre is nagyon köszönöm a segítséget!
Szanyi Judit
judit.szanyi@ju-ditta.hu

**Comment by iamgergo** [comment]
@Csutszika Kedves Judit,

Ha tippelnem kellene, akkor a szállítási dolognál csúszik el valami.
Ezt a bővítmény minden esetben "keresi", holott virtuális termék esetében szállítás nincs.

Hamarosan utána nézek, remélhetőleg tudjuk orvosolni a problémát.

Köszönöm!

**Comment by iamgergo** [comment]
@Csutszika Valóban nekem is előjött virtuális termék esetén a hiba. Ha minden igaz sikerült javítani, nálam már működik csak virtuális és vegyes termékek esetén is.

Kikerült a frissítés ami kezeli ezt az eshetőséget is, így a bővítmény frissítése után ennek a hibának már nem kellene élnie.

@summeritsoft Lehet, hogy nektek is hasonló okból jött elő a hiba?

**Comment by Csutszika** [comment]
@iamgergo 
Ez nagyon gyors volt! :) Hálás köszönet! 
A frissítést még nem ajánlja fel a Wordpress bővítményei között. Töltsem le a weboldalatokról?
Köszönöm!
Judit

**Comment by iamgergo** [comment]
@Csutszika A frissítést a WP fel fogja dobni – néha ez akár több óra is lehet, teljesítmény optimalizálás miatt. Ha nem szeretnéd megvárni, akkor nyugodtan letöltheted és törlés után újra tudod telepíteni.

Ha esetleg hiba merülne fel, jelezd nyugodtan!

Köszönjük!

**Comment by Csutszika** [comment]
@iamgergo
Ja, értem. Akkor megvárom türelmesen. :) Majd visszajelzek, hogy minden rendben van e.
Köszönöm még egyszer!
Judit

**Comment by Csutszika** [comment]
@iamgergo
Kedves Gergő! Tökéletesen működik. :) Már az OTP is lefuttatta a szokásos köreit, minden rendben. 
Köszönöm szépen!
Judit

**Comment by iamgergo** [comment]
Szuper, nagyon örülök!
