### ISSUE TITLE
Mennyiség: 0,5 - Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by varadiv** [thepinecode/simplepay-gateway#26]
Üdvözlet,
Teszt üzemben futottam bele abba a problémába, hogy amennyiben a kosárban egy termékből kevesebb, mint 1 egység van (pl. 0,5 méter), akkor a fizetésnél: "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra." hibaüzenetet kapok. Csak 1 egység alatt van probléma, pl. 1,5 méter termék esetében már rendben átirányít a webshop a fizető felületre. 2x 0,5 méter vagy 1x 1 méter + 1x 0,5 méter terméknél jelentkezik a hibaüzenet.
Woocommerce (termék) beállítási probléma lehet?
A mennyiségi egységek beállítására a [Quantities and Units for WooCommerce](https://wordpress.org/plugins/quantities-and-units-for-woocommerce/) plugint használom.

Előre is nagyon köszönöm a segítséget!
Váradi Viktor

**Comment by iamgergo** [comment]
Kedves Viktor,

Köszönjük a visszajelzést. Hamarosan utánanézek a problémának, remélhetőleg gyorsan tudjuk javítani.

**Comment by iamgergo** [comment]
@varadiv A probléma kicsit összetettebb lett mint hittem. A hiba az OTP oldalán van, még pedig az, hogy nem kezelik a nem egész mennyiségi értékeket.

A megoldás az, hogy a SimplePay-nek mindig egész számot adunk át mint mennyiség. Az értéket felfelé kell kerekíteni, hogy az árazással is rendben működjön. Tehát `0,5` esetén `1` lesz, `2,2` esetén `3` és így tovább.

Természetesen a Woo oldalán ez megfelelően megjelenik, tehát a készletkezelés ott megfelelően fog működni, de hogy a fizetés is megfelelően működjön ez csak így lehetett megoldani.

Kikerült egy frissítés, amivel nekem már működött megfelelően. Frissítés után ezt te is meg tudod erősíteni?

**Comment by szepeviktor** [comment]
Ez az: https://github.com/thepinecode/simplepay-gateway/releases/tag/v2.2.4

**Comment by varadiv** [comment]
Köszönöm a gyors segítséget, rendben működik!
