### ISSUE TITLE
Funkcionális teszt

### ISSUE THREAD

**Issue by szepeviktor** [thepinecode/simplepay-gateway#3]
Mivel pénzt kezel ez a plugin, lesz olyan funkcionális (nem unit) teszt, ami WP és WC telepítés után CI-ban is lefuttatható?

TravisCI-ban vagy [GitHub Actions](https://github.com/features/actions)-ben lehet titkos adatokat tartani, amivel elérhetnénk az OTP sandbox-ot.

**Comment by iamgergo** [comment]
Ehhez kellene kérni egy fiókot az OTP-től, valamint kellene egy állandó endpoint amit beállítunk a SimplePay oldalán.

**Comment by szepeviktor** [comment]
Az OTP bizonyára nagy örömmel veszi, hogy 

- van ingyenes Woo plugin
- tesztelni is akarjuk!

Az endpoint -> https://ngrok.com/

**Comment by iamgergo** [comment]
Most teszteléshez én is ngrokot alkalmazok, az jó lehet, de csak 8 óráig érvényes az URL.
Én megkérdezem, az OTP-t hátha adnak egy tesztfiókot szerződés nélkül.

**Comment by szepeviktor** [comment]
A CI csak percekig futna.

**Comment by iamgergo** [comment]
Azt értem, de a simplepay oldalán be kell állítani az URL-t. Nem szívesen lépnék be minden egyes teszt előtt és frissíteném a beállításokat.

**Comment by iamgergo** [comment]
Vagy tudjuk kontrollálni, hogy milyen URL-t generáljon?

**Comment by szepeviktor** [comment]
Akkor inkább Now-val csináljuk: https://zeit.co/now

**Comment by iamgergo** [comment]
Rendben, akkor erre térjünk vissza, ha kaptam választ a SimplePaytől.

**Comment by szepeviktor** [comment]
Itt találtam MERCHANT + SECRET_KEY-t

https://www.simplepay.hu/fejlesztoknek > Demo kereskedői fiók csatlakozási adatok.PDF

**Comment by iamgergo** [comment]
Az nem jó. Az OTP-nek kell írni, ha nem adnak fiókot akkot kuka.

**Comment by iamgergo** [comment]
Szerződés nélkül nem kapunk adatokat.
