### ISSUE TITLE
Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by dosabalint** [thepinecode/simplepay-gateway#30]
Sziasztok,

Egy webshopnál elkezdtük használni a plugint (amiért végtelenül hálásak vagyunk, hogy van <3).
Egyik hétről a másikra a checkout lapon hibát kaptunk ennél a fizetési módnál.

Logba ez került:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in
/var/www/clients/client6/web80/web/wp-content/plugins/simplepay-gateway-master/src/Requests/Request.php:70
```

Ez volt az amit tömbként próbált kezelni:
```
WP_Error Object (
    [errors] => Array (
        [http_request_failed] => Array (
            [0] => cURL error 60: SSL certificate problem: certificate has expired
        )
    )
    [error_data] => Array ( )
)
```

Erről a checkout oldalon egy ilyen szöveget kaptunk notification formájában:
`INTERNAL SERVER ERROR`

Csak feedback-ként terveztem ezt itt hagyni, hogy ilyenbe futottunk.

Köszönjük a munkátokat! Legjobbakat!

**Comment by ucsendre** [comment]
> Feladó: SimplePay ügyfélszolgálat <ugyfelszolgalat@otpmobil.com> 
> Küldve: 2020. május 31. 0:00
> Tárgy: SimplePay tájékoztatás tanúsítvány ellenőrzéséről

Tisztelt Partnerünk!
 
Ezúton tájékoztatjuk Önt, hogy az OTP Mobil Kft. által üzemeltetett SimplePay fizetési felületének tanúsítvány kiadója (Comodo/Sectigo) lecserélte az eddig használt ROOT CA tanúsítvány lánc egyes elemeit.
 
A tanúsítvány kiadója (Comodo/Sectigo) eddig használt tanúsítványa 2020.05.30-án lejárt, az új ROOT CA tanúsítvány elemek implementálása az OTP Mobil Kft. saját tanúsítványával egy időben már automatikusan megtörténtek a SimplePay rendszerben.
 
Kérjük ellenőrizzék, hogy az Önök webáruházából megfelelően megnyílik-e a SimplePay fizetőoldal. Amennyiben a fizetési felület betölt, az Önök rendszere is sikeresen frissítette a tanúsítványlánc új elemeit.
 
Abban az esetben, ha a fizetőoldal nem tölt be megfelelően ("Transaction does not exist" hibaüzenet jeleni meg a fizetőoldal helyett), kérjük levelünket továbbítsa weboldala/webáruháza üzemeltetője, vagy webshop szolgáltatója felé, és manuálisan végezzék el a tanúsítványlánc frissítésének implementálását.
 
A tanúsítvány az alábbi oldalról tölthető le, és frissíthető: https://support.sectigo.com/articles/Knowledge/Sectigo-Intermediate-Certificates?retURL=%2Fapex%2FCom_KnowledgeWeb2Casepagesectigo&popup=false
 
Kérdés esetén kérjük keresse kollégáinkat az itsupport@otpmobil.com e-mail címen.
 
 
Üdvözlettel,
a SimplePay csapata
Budapest, 2020. május 30.

**Comment by dosabalint** [comment]
Köszi, a certes szál már megvan.
Ezt az issue-t inkább amiatt írtam, ahogy az errort kezeli a plugin.

**Comment by iamgergo** [comment]
@dosabalint Köszönjük a visszajelzést, nagyon hasznos infó! Hamarosan megoldjuk a hibakezelést.

**Comment by iamgergo** [comment]
Kikerült az új verzió. Kicsit átalakítottuk a lekéréseket, amelyek már kezelik azt az esetet is, ha a válasz egy `WP_Error` objektum. Ha esetleg félrement valami, jelezzétek nyugodtan. Köszi!
