### ISSUE TITLE
WooCommerce 4.2 nem működő plugin

### ISSUE THREAD

**Issue by materozsa** [thepinecode/simplepay-gateway#32]
Sziasztok!

Most szeretném tesztelni majd a fizetési kaputokat, de azt vettem észre, hogy a woocommerce 4.2 es kiadásában nem működik a plugin.

Üdv.: Máté

**Comment by iamgergo** [comment]
Szia!

Mi nem tapasztalunk rendellenességet a 4.2-vel sem. Pontosan mi a gond, mi nem megy?
Esetleg a log tartalmaz valami releváns infót?

**Comment by materozsa** [comment]
localhostra telepítettem egy friss wordpresst + woocommerce-t és nem jelent meg a woocommerce fizetési beállításokban a Simple pay, a pluginok között is csak a kikapcsolás gomb az aktív. Az élő weboldalon régebbi a woocommerce ott fut megfelelően. De akkor délután megnézem, hogy mit ronthattam el. Köszönöm a visszajelzést!

**Comment by iamgergo** [comment]
Esetleg annyi lehet, hogy ha a nem bevett módon telepítetted – pl át lett nevezve a bővítmény mappa neve – akkor abból lehet gond. De elvileg annak sem kellene problémáznia.

**Comment by materozsa** [comment]
Git clone al adtam hozzá a a pluginek mappához. Átírtam "simplepay-gateway-master"-re a mappa nevét és már működött is. Köszönöm a segítséget!
