### ISSUE TITLE
Külső hivatkozási szám: wc_order_xxxxxxxxxxxxx

### ISSUE THREAD

**Issue by varadiv** [thepinecode/simplepay-gateway#33]
Sziasztok,
Szeretnék érdeklődni, hogy van-e arra lehetőség, hogy az order_key helyett az orderid legyen átadva a simplepay részére, mint külső hivatkozási szám? A jelenlegi wc_order_xxxxxxxxxxxxx formátum helyett esetleg egyedi prefix+orderid formátum használatára van-e lehetőség? Köszönöm előre is!

**Comment by iamgergo** [comment]
Szia! 

Ez az igény már többedjére merül fel, így megnézzük mit tudunk tenni. Hamarosan jelzem, hogy mire jutottunk. 

Köszi!

**Comment by iamgergo** [comment]
Szia! 

A most kikerült új verzió már a rendelés azonosítót használja a kulcs helyett, valamit be lehet állítani az egyedi prefixet is a beállítások alatt. Lehet üres prefixum is, akkor csak simán a rendelés ID-t kapja a SimplePay.

**Comment by varadiv** [comment]
Sziasztok,
Köszönet a gyors módosításért, szuper lett!
Tesztelés közben azt látom, hogy sikeres fizetést követően a simplepay oldal a Pénztárba irányít vissza és nem a Sikeres megrendelés oldalra. Lehet, hogy az order_key miatt?
A megrendelés egyébként az e-mail értesítések alapján sikeres lesz.
Köszi előre is!

**Comment by iamgergo** [comment]
Érdekes én ezt nem tapasztalom!
Pontosan milyen prefixet állítottatok be?

**Comment by varadiv** [comment]
TA-
Ez volt az egyik pl.:
Külső hivatkozási szám: | TA-525

**Comment by varadiv** [comment]
Teszteltem több esetet is és arra jutottam, hogy a hiba csak abban az esetben jelentkezik, ha a prefix-ben nagy betű van. Remélem ez segít!

**Comment by iamgergo** [comment]
Valóban! Kiment a javítás! Meg tudod erősíteni, hogy rendben működik? Köszi!

**Comment by varadiv** [comment]
Köszönöm! Várom a v2.3.3 release-t és megnézem!

**Comment by varadiv** [comment]
Megérkezett a frissítés! Köszönöm, rendben működik!

**Comment by iamgergo** [comment]
Szuper, köszi a közreműködést!
