### ISSUE TITLE
Fizetés folyamatban statusz

### ISSUE THREAD

**Issue by kukac7** [thepinecode/simplepay-gateway#34]
hello

olyan problemam lenne, hogy sandboxban, vegigmegy a fizetes, visszater az otp feluleterol a user, nem ir hibat, de az wc admin-on csak annyi van, hogy "Fizetés folyamatban".
ennek nem kellene mas statuszunak lennie?

koszi!

**Comment by iamgergo** [comment]
Szia!

Mit ad az IPN? Az állítja be a rendelés állapotát. Ez nem akkor történik amikor a user visszatér a formról.

**Comment by kukac7** [comment]
@iamgergo `https://webshop.hu/wp?wc-api=wc_gateway_simplepay-gateway`
ez van beallitva otp oldalon is es elvileg jol.

**Comment by iamgergo** [comment]
Az IPN üzenet tartalma az érdekes. Meg tudod nézni az egyes tranzakciókhoz tartozó IPN küldés válaszát. Ott az szerepel, hogy "OK."?

**Comment by kukac7** [comment]
@iamgergo hiaba kapcsoltam be a loggolast a plugin-ben, nincs semmi. vagy hol kellene latnom?

kozben az otp valaszolt ennyit:
> ... weboldalán indított az alábbiakban részletezett rendelést a vásárló sikeresen rendezte. Mindazonáltal az Ön rendszerének kiküldött IPN üzenet többszöri próbálkozás után sem lett sikeresen visszaigazolva. Kérjük ellenőrizze az IPN beállításokat.

**Comment by iamgergo** [comment]
Az OTP admin felületén, amikor a tranzakció aloldalán van ez a fül:
<img width="720" alt="Képernyőfotó 2020-06-15 - 15 34 25" src="https://user-images.githubusercontent.com/6567179/84663711-d0c97f00-af1d-11ea-9dde-a90bed8e7cd1.png">

Tehát nem a Wooban, hanem a SimplePay adminban kell keresni az IPN adatokat. Ha nem megfelelő az IPN válasz, akkor meg lehet nézni a hibát.

**Comment by kukac7** [comment]
sajnos nincs hozzaferesunk az otp adminhoz, de probalunk tobb infot megtudni.

addig is, annyit tudok mondani, hogy jon a vasarlas utan otp level:

> ...weboldalán érkezett rendelést az alábbi tranzakcióval sikeresen rendezte.

nem tudom, ez segit e.

**Comment by iamgergo** [comment]
Értem. Sajnos nem sokat segít. Én nem tapasztalom a hibát, és máshonnan sem kaptunk visszajelzést ezzel kapcsolatban, így szerintem valami nálatok mehet el. Érdemes csekkolni, hogy nincs-e szóköz az IPN url-ben például. De ezt is csak az adminon lehet csekkolni...

Innen többet sajnos nem tudok segíteni.

**Comment by kukac7** [comment]
kozben nyomoztunk szerver oldalon.

```[2020-06-15T10:42:04+02:00] x.x.x. webshop.hu "GET /wp/?wc-api=wc_gateway_simplepay-gateway HTTP/1.1" 200 0.739 39 "Apache-HttpAsyncClient/4.1.1 (Java/1.8.0_232)" "-"```

```[2020-06-15T11:06:48+02:00] x.x.x.x webshop.hu "GET /wp/?wc-api=process_simplepay_payment&r=eyJyIjowLCJ0IjoxMDMyMDUzMSwiZSI6IlNVQ0NFU1MiLCJtIjoiT01TNTQ0MjUwMSIsIm8iOiJ3Y19vcmRlcl9HUGNOZnl3U1A5MG83In0%3D&s=XtK0HiqxuIquQTwPI37a9X%2FhfVBglVFv2pl4tg6TevYXrP992knWtQnoXnZ%2FHgpC HTTP/2.0" 302 0.362 473 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" "https://sandbox.simplepay.hu/pay/pay/pspHU/lp55xzme0LyO"```

```[2020-06-15T11:06:49+02:00] x.x.x.x webshop.hu "GET /penztar/rendeles-fogadva/9637/?key=wc_order_GPcNfywSP90o7 HTTP/2.0" 200 0.460 11231 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" "https://sandbox.simplepay.hu/pay/pay/pspHU/lp55xzme0LyO"```

```[2020-06-15T11:06:50+02:00] x.x.x.x webshop.hu "POST /?wc-ajax=get_refreshed_fragments HTTP/2.0" 200 0.338 740 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" "https://webshop.hu/penztar/rendeles-fogadva/9637/?key=wc_order_GPcNfywSP90o7"```

**Comment by iamgergo** [comment]
Szerintem pont azt mutatja, hogy nem jó. Részlet a dokumentációból:

> Az Instant Payment Notification (ipn) a fizetési tranzakció vége. Ezen a ponton tájékoztatja a SimplePay rendszere a kereskedő webáruházát a tranzakció sikerességéről. A sikeres fizetés után **POST** metódussal küld üzenetet a SimplePay szervere a kereskedő részére.

Tehát az IPN egy POST kérést fog küldeni nem pedig GET-et. Ti pedig GET-et kaptatok a log alapján. A másik, hogy ha lett volna IPN kérés, és a log is be volt kapcsolva, akkor a kérés esemése logolva lett volna a naplóban. Emellett, az időbélyegek alapján a vásárlás előtt volt kérés az URL-en és nem utána, tehát ez nem lehet az adott rendelés IPN-je.

Most csináltam még egy tesztvásárlást, és továbbra sem tapasztalom, hogy ne állítaná át a rendelés állapotát.

Szerintem, ha valahogy sikerül hozzájutni a simplepay adminhoz, többet tudtok majd. Ha mégis kideül, hogy nálunk a hiba, akkor kérlek jelezd, és újranyitom az issuet.

Köszi!

**Comment by kukac7** [comment]
kozben lett otp admin hozzaferes es latszodnak a hibak.

```Result CONTENTNOTMATCHSignature NO_SIGNATUREResponse A rendelés nem található.Index 2Finished 2020.06.17 15:14:37IPN URL https://webshop.hu/wp?wc-api=wc_gateway_simplepay-gatewaySent IPN hash {"salt":"u2GtHsOtJixEXbRPBtIDFuX6mtI3IgFh","orderRef":"wc_order_kBzxtAdbxIFt5","method":"CARD","merchant":"OMS5442501","finishDate":"2020-06-17T15:14:31+02:00","paymentDate":"2020-06-17T15:14:14+02:00","transactionId":10323341,"status":"FINISHED"}Response status code 200```

mi lehet a problema?

**Comment by iamgergo** [comment]
A tegnapi frissítéssel megváltozott az orderRef kezelése, így ezért nem találja a rendelést – abban az esetben ha már frissítettetek, de a rendelés még egy korábbi verzióval lett leadva.

Szerintem az almappa kavarhatott be, én is nginx alatt futtatom a teszteket.
De örülök, hogy megoldódott!

**Comment by kukac7** [comment]
ha nem szolsz, nem latom, hogy van uj frissites. nem jelezte.
szoval meg az elozo verzioval probalkoztunk.

de ahogy nezem, pl. ha kiszedem az almappat es csak a site url van, akkor is jol mukodik.
szoval lehet az ipn url mutatasnal jobb lenne a site url es nem a wp url.

koszi!

**Comment by wphonlap** [comment]
Hello, én is ezzel küzdök jónéhány napja.

Nálam nem 200, hanem 503 a válasz.

Eredmény NOT200 
Signature NO_SIGNATURE 
Fogadott válasz 
Index 2 
Időpont 2020.10.02 02:53:00 
IPN URL https://shop.hu/?wc-api=wc_gateway_simplepay-gateway 
Elküldött IPN tartalma {"salt":"9Bi390MlbE8JFMLohXRv24llN54lCktN","orderRef":"wc-2080","method":"CARD","merchant":"S252601","finishDate":"2020-10-02T02:52:43+02:00","paymentDate":"2020-10-02T02:51:10+02:00","transactionId":109825430,"status":"FINISHED"} 
Válasz HTTP kódja 503

A debug.log-ban csak ennyit látok: PHP Notice:  Undefined index: section in /home/user/public_html/wp-content/plugins/simplepay-gateway-master/src/Gateway.php on line 301
Az access.log-ban: 94.199.53.96 - - [02/Oct/2020:00:53:00 +0000] "POST /?wc-api=wc_gateway_simplepay-gateway HTTP/1.1" 503 0 "-" "Apache-HttpAsyncClient/4.1.1 (Java/1.8.0_252)"

Ha SP adminban az IPN küldésre katt, ezt látom: ??payment.NOT200_hu_HU??

Próbáltam biztonsági beállítások kiiktatásával, alap .htaccess-el. Próbáltam másik szerveren, ott is 503. (Az egyik GCP, a másik Hetzner.) Szerveresek is kerestek okot, nem találtak. PHP-som postman kérést küldött az IPN URL-re, az 200-at ad vissza.

Minden a legfrissebb.
Lassan kifogyok az ötletekből.
