### ISSUE TITLE
multisite funkció

### ISSUE THREAD

**Issue by guzmosz** [thepinecode/simplepay-gateway#39]
nagyon hasznos lenne számomra

**Comment by guzmosz** [comment]
Úgy tűnik, hogy működik csak nem központilag kell bekapcsolni, hanem aldomainenkét.

**Comment by iamgergo** [comment]
Szia!

Igen, ahogy tesztelem most én is ugyan ezt tapasztalom.
Megpróbálom megoldani a központosítást is, ha siker akkor jelzek.

Köszi a visszajelzést.

**Comment by iamgergo** [comment]
Ha minden igaz sikerült javítani, így zárom az hibajegyet. Ha mégis feljön valami, akkor jelezd nyugodtan.

Köszi!

**Comment by guzmosz** [comment]
Szuper 

Köszi!
