### ISSUE TITLE
Magyar README

### ISSUE THREAD

**Issue by szepeviktor** [thepinecode/simplepay-gateway#4]
Bizonyára sok fejlesztőnek nehézség, hogy angolul értse meg, mi a csízió.

**Comment by iamgergo** [comment]
Ez nem fejlesztőknek készült, de jó ötlet a magyar readme!

**Comment by iamgergo** [comment]
Bár az angolt is megtartanám mindenképpen.

**Comment by szepeviktor** [comment]
Ha felhasználóknak, akkor egy [ritmusos telepítési videót](https://www.youtube.com/watch?v=RZjIQtn13Vw) kell csináljunk.

**Comment by iamgergo** [comment]
Nagyon ráérünk még azzal.

**Comment by iamgergo** [comment]
Readme helyett a WordPress popupban helyezzük el a magyar lerírás.
