### ISSUE TITLE
Undefined property: Pine\SimplePay\Gateway::$show_icon

### ISSUE THREAD

**Issue by ucsendre** [thepinecode/simplepay-gateway#41]
Sziasztok!

Ez kerül a wp debug logjába kb minden oldalbetöltéskor:
`PHP Notice: Undefined property: Pine\SimplePay\Gateway::$show_icon in /wp-content/plugins/simplepay-gateway-master/src/Gateway.php on line 120`

SimplePay Gateway for WooCommerce version:	2.4.1

WordPress version:		5.5
WooCommerce version:		4.3.3
WooCommerce REST API package:		 1.0.10 
WordPress memory limit:		256 MB
Language:		hu_HU
Server info:		nginx/1.18.0
PHP version:		7.4.8
PHP post max size:		50 MB
Max upload size:		50 MB
PHP time limit:		90
PHP max input vars:		3000
cURL version:		7.29.0, NSS/3.44
MySQL version:		5.5.5-10.2.33-MariaDB

Tudnátok segíteni megállapítani, hogy mi a hiba?

Köszönöm!
Üdv,
Endre

**Comment by iamgergo** [comment]
Szia!

A legfrissebb verzióval bekerült egy olyan opció, hogy a checkoutnál meg lehet jeleníteni a SimplePay icont.
Úgy néz ki, hogy kell egy extra isset() ha nincs beállítva ilyen opció. 

Hamarosan javítjuk, köszi, hogy jelezted.

**Comment by iamgergo** [comment]
@ucsendre Elvileg javítva, a 2.4.2-vel már bekerült az extra check. Ha mégis felmerül valami, akkor jelezd kérlek, és újranyitom a jegyet.

Köszi!
