### ISSUE TITLE
Class 'WC_Payment_Gateway' not found

### ISSUE THREAD

**Issue by ucsendre** [thepinecode/simplepay-gateway#5]
Sziasztok!

Leszedtem a legutóbbi release verziót és felraktam ezt a plugint a teszt wp oldalamra, de aktiváláskor azonnal elszállt tőle a wp. Másodszor megpróbáltam a jelenlegi "master" verziót is, ugyanaz a hiba.
Az alábbi hibát (és figyelmeztetéseket) produkálta:
`[30-Jul-2019 14:42:22 UTC] PHP Notice:  Undefined index: debug in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Support\ConfigManager.php on line 68
[30-Jul-2019 14:42:22 UTC] PHP Notice:  Undefined index: sandbox in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Support\ConfigManager.php on line 69
[30-Jul-2019 14:42:22 UTC] PHP Notice:  Undefined index: debug in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Support\ConfigManager.php on line 68
[30-Jul-2019 14:42:22 UTC] PHP Notice:  Undefined index: sandbox in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Support\ConfigManager.php on line 69
[30-Jul-2019 14:42:22 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Payment_Gateway' not found in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Gateway.php:13
Stack trace:
#0 C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\autoload.php(14): require_once()
#1 [internal function]: {closure}('Pine\\SimplePay\\...')
#2 C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Plugin.php(38): spl_autoload_call('Pine\\SimplePay\\...')
#3 C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\simplepay-gateway.php(24): Pine\SimplePay\Plugin::boot()
#4 C:\xampp\htdocs\teszt-nyomika\wp-settings.php(362): include_once('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\teszt-nyomika\wp-config.php(59): require_once('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\teszt-nyomika\wp-load.php(37): require_once('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\teszt-nyomika\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\teszt-nyomika\wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...')
#9 {main}
  thrown in C:\xampp\htdocs\teszt-nyomika\wp-content\plugins\simplepay-gateway\src\Gateway.php on line 13
`
Tudnátok segíteni, hogy mit rontottam el?

**Comment by iamgergo** [comment]
Szia!

Milyen PHP verziót használsz?

Hamarosan frissítem a repót, hogy az alábbi hiba ne fordulhasson elő alacsonyabb PHP esetén sem, vagy más környezeti beállítások hatására.

Akkor hamarosan jelentkezem!
Köszi!

**Comment by iamgergo** [comment]
@ucsendre Masterre kikerült egy frissítés, nyugodtan használd azt, a releasek csak jelzés értékűek.

Ha továbbra is jelenzkezik hiba, itt tudod jelezni.

Köszönöm!

**Comment by ucsendre** [comment]
Szia Gergő!

Köszönöm a gyors javítást! Ez a verzió működik. Figyelmeztetéseket továbbra is dobál a logba, de hibát eddig nem tapasztaltam.
A teszt környezetem: XAMPP Version: 7.3.6 win10 home 64biten
Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.6
WP: 5.2.2, WC: 3.6.5, sablon: OceanWP 1.6.8

Üdv,
Endre

**Comment by iamgergo** [comment]
Remek, örülök!

Milyen figyelmeztetést dobál? Hátha azt is gyorsan lehet javítani.

Köszönöm!

**Comment by ucsendre** [comment]
Bekapcsoltam a beállításoknál a hibakereső naplózást, ami ezt eredményezi:

`[31-Jul-2019 08:46:57 UTC] WC_Log_Handler_File::get_log_file_path was called incorrectly. Ez a függvény nem hívható a plugin-ok betöltése (plugins_loaded hook) előtt. Backtrace: require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/simplepay-gateway-master/simplepay-gateway.php'), Pine\SimplePay\Plugin::boot, Pine\SimplePay\Gateway->__construct, Pine\SimplePay\Gateway->init_form_fields, include('/plugins/simplepay-gateway-master/includes/fields.php'), WC_Log_Handler_File::get_log_file_path, wc_doing_it_wrong. This message was added in version 3.0.`

**Comment by ucsendre** [comment]
Ezt találtam egy másik payment gateway __construct() füvvényében:
`$this->log = new WC_Logger();`
Ott működik a log.

**Comment by iamgergo** [comment]
Szuper, köszönöm!

Sokkal egyszerűbbnek találtam, hogy  csak kiemeltem a prefixumot, mert az elérési útvonal minden nap változik.

Köszi a segítséget! 
Masteren kint van a legfrissebb commit.

**Comment by kohanyirobert** [comment]
> PHP Fatal error:  Class 'WC_Payment_Gateway' not found in /home/user/public_html/wp-content/plugins/simplepay-gateway/src/Gateway.php on line 14

Hasonló hibát észleltem, mint az itt említett. A PHP v5.6.40 verzióval rendelkezem (shared hosting). Gondolom ez a probléma. Latest masterrel próbáltam ([ezzel](02c3d7479e0336254af8b0f6cd58ea994e461ed3)). Létezik, hogy ezzel működésre lehet bírni?

**Comment by iamgergo** [comment]
@kohanyirobert Szia!

Mi a pontos hibaüzenet? Elvileg kompatibilis azzal a PHP verzióval, de támogatást csak PHP 7+-hoz tudunk biztosítani a jövőben.

**Comment by kohanyirobert** [comment]
Pont ez, amit írtam. (Azóta kipróbáltam PHP 7+-al is, de ue. kapom.)
Milyen WooCommerce verzió a követelmény?

**Comment by iamgergo** [comment]
@kohanyirobert Értem, azt hittem, hogy "hasonló". Mennie kellene 3.7.0-s verzióval, és is azzal használom.

Szerintem ez azért lehet, mert a SimplePay bővítményt hamarabb betölti mint a Woo-t. Ennek elvileg nem szabadna előfordulnia a `Plugin::guard()` miatt, de olyan mintha mégis ez történne.

Nem tudom, hogy a Woo / SimplePay ki-be kapcsolgatást próbáltad-e, ha nem lehet, hogy megér egy próbát.

Van olyan bővítmény ami konfliktust okozhat?

**Comment by kohanyirobert** [comment]
@iamgergo Ki-bekapcsolgatni nem tudom a plugint. Ha bekapcsolom onnantól a WordPress is lehal (DEBUG mód bevan kapcsolva, lehet ez a gond?)

**Comment by iamgergo** [comment]
@kohanyirobert Rendben, szólj kérlek ha van valami eredmény! Köszi!

**Comment by kohanyirobert** [comment]
Kérdés: telepítésnél elég a `wp-content/plugins` mappába klónoznom a repót?

Ha kikapcsolok minden plugint, csak a SimplePay marad, akkor annyi változás van, hogy ha megpróbálom ezt bekapcsolni, akkor nem döglik meg tőle a WP, csak kiírja a Plugins page tetején a korábbi hibát

```
[19-Nov-2019 06:17:16 UTC] PHP Fatal error:  Class 'WC_Payment_Gateway' not found in /home/user/public_html/wp-content/plugins/simplepay-gateway/src/Gateway.php on line 14
```

Tehát ilyenkor kivan kapcsolva a WooCommerce plugin is. Ha ezt bekapcsolom és úgy kapcsolom be a SimplePay-t, akkor is ue. a hiba, csak megdöglik a WP felülete teljesen (le kell törölnöm a plugint kézzel).

**Comment by iamgergo** [comment]
@kohanyirobert Köszi!

Ha nem kónozod hanem letöltöd a plugint és az eredeti nevét `simplepay-gateway-master`-t használod akkor is kijön a hiba?

Csak azért, mert amikor ki-be kapcsolódik a plugin akkor próbálja magát a sor végére rendezni, hogy a woo biztosan előbb töltődjön be mint a SimplePay. De ha át van neveze, akkor lehet ez megborul.

Mindenesetre keresni fogok egy megoldást ami megoldja ezt a problémát. 

Köszi az infókat!

**Comment by kohanyirobert** [comment]
A `simplepay-gateway-master` név használatával is működik.
