### ISSUE TITLE
Időtúllépés esetén nem jelenik meg a "cancelled" notice

### ISSUE THREAD

**Issue by kohanyirobert** [thepinecode/simplepay-gateway#7]
Időtúllépés esetén a SimplePay oldalról visszairányítódik a felhasználó a kereskedő oldalra és meghívódik a [`notifyCancelled`](https://github.com/thepinecode/simplepay-gateway/blob/master/src/Gateway.php#L262) függvény (az `if` ágba kerül a végrehajtás, tehát a feltételvizsgálat `true`, erről meggyőződtem).

Azonban az üzenet nem jelenik meg a "kassza", fizetés oldalon, ahová visszakerül a felhasználó. (Megj.: sikeres vagy sikertelen fizetés esetében működik).

Mi lehet a gond?

**Comment by iamgergo** [comment]
@kohanyirobert Szia!

Köszi az infót! Amint időm engedi, megnézem!
Ha addig találsz megoldást esetleg, nyugodtan nyiss rá egy PR-t.

Köszi

**Comment by kohanyirobert** [comment]
Hmm, úgy tűnik benéztem valamit. Azt írtam hivatkozott feltétel igazra értékelődik ki ... mégsem. (Nem tudom mit csináltam, hogy mégis ez történt.)

Viszont ez `if (isset($_GET['cancelled'], $_GET['redirect'])) {` nem működik. Ez viszont igen `if (isset($_GET['cancelled'])) {` (legalábbis az én esetemben.

Nem vagyok benne biztos, hogy ez minden esetben kielégítő, de csináltam egy PR-t.

**Comment by iamgergo** [comment]
Köszönöm!

Szerintem jónak néz ki!
